[package]
name = "rbrt"
version = "0.1.0"
authors = ["Stefan Baur <stefan.a.baur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
rbrt_lib = {path = "rbrt_lib"}
clap = "2"
image = "0.12"
